development:
  adapter: postgresql
  database: divebook_development
  pool: 5
  timeout: 5000
  username: administrador
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: divebook_test
  pool: 5
  timeout: 5000
  username: administrador
  host: localhost
  port: 5432